# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
sudo: required
warnings_are_errors: false

r_packages:
  - covr

before_install:
  - sudo apt-get update -qq

matrix:
  include:
  - r: devel
    after_success:
    - R CMD INSTALL .
    - Rscript -e 'remotes::install_github("rstudio/rmarkdown", upgrade = "never")'
    - Rscript -e 'pkgdown::build_site()'
    - Rscript -e 'covr::codecov()'
    deploy:
      provider: pages
      skip-cleanup: true
      github-token: $GITHUB_PAT
      keep-history: true
      local-dir: docs
      on:
        branch: master

