# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

after_success:
  - Rscript -e 'covr::codecov()'
  - R CMD INSTALL .
  - Rscript -e 'pkgdown::build_site()'
